In [47]:
import pandas as pd

In [48]:
df=pd.read_csv('premier-player-23-24.csv')
df.head(5)

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,Ast_90,G+A_90,G-PK_90,G+A-PK_90,xG_90,xAG_90,xG+xAG_90,npxG_90,npxG+xAG_90,Team
0,Rodri,es ESP,MF,27.0,34,34,2931.0,32.6,8.0,9.0,...,0.28,0.52,0.25,0.52,0.12,0.12,0.24,0.12,0.24,Manchester City
1,Phil Foden,eng ENG,"FW,MF",23.0,35,33,2857.0,31.7,19.0,8.0,...,0.25,0.85,0.60,0.85,0.33,0.26,0.59,0.33,0.59,Manchester City
2,Ederson,br BRA,GK,29.0,33,33,2785.0,30.9,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester City
3,Julián Álvarez,ar ARG,"MF,FW",23.0,36,31,2647.0,29.4,11.0,8.0,...,0.27,0.65,0.31,0.58,0.44,0.22,0.66,0.39,0.61,Manchester City
4,Kyle Walker,eng ENG,DF,33.0,32,30,2767.0,30.7,0.0,4.0,...,0.13,0.13,0.00,0.13,0.01,0.09,0.10,0.01,0.10,Manchester City

In [49]:
df2=pd.read_csv('players.csv')
df2.head()

,id,name,now_cost,position,team,web_name,transfers_in_event,influence_rank_type,news_added,ict_index_rank_type,...,now_cost_rank_type,ict_index,now_cost_rank,minutes,yellow_cards,cost_change_event_fall,red_cards,value_form,ict_index_rank,total_points
0,1,Folarin Balogun,44,FWD,Arsenal,Balogun,0,61,2023-08-31T08:55:15.272751Z,63,...,94,0.0,528,0,0,0,0,0.0,628,0
1,2,Cédric Alves Soares,39,DEF,Arsenal,Cédric,433,173,NaN,172,...,231,0.0,729,0,0,0,0,0.0,493,0
2,3,Mohamed Elneny,44,MID,Arsenal,M.Elneny,54,215,2023-12-12T22:30:08.433665Z,214,...,290,0.4,498,1,0,0,0,0.0,470,4
3,4,Fábio Ferreira Vieira,54,MID,Arsenal,Fábio Vieira,5,134,2023-12-07T12:00:08.489004Z,139,...,80,21.9,127,236,0,0,1,0.0,300,21
4,5,Gabriel dos Santos Magalhães,49,DEF,Arsenal,Gabriel,104278,42,2023-09-30T23:00:07.672676Z,47,...,31,43.3,247,1284,1,0,0,0.9,172,56

In [50]:
city1=df[df['Team']=='Manchester City']
city1.head()

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,Ast_90,G+A_90,G-PK_90,G+A-PK_90,xG_90,xAG_90,xG+xAG_90,npxG_90,npxG+xAG_90,Team
0,Rodri,es ESP,MF,27.0,34,34,2931.0,32.6,8.0,9.0,...,0.28,0.52,0.25,0.52,0.12,0.12,0.24,0.12,0.24,Manchester City
1,Phil Foden,eng ENG,"FW,MF",23.0,35,33,2857.0,31.7,19.0,8.0,...,0.25,0.85,0.60,0.85,0.33,0.26,0.59,0.33,0.59,Manchester City
2,Ederson,br BRA,GK,29.0,33,33,2785.0,30.9,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester City
3,Julián Álvarez,ar ARG,"MF,FW",23.0,36,31,2647.0,29.4,11.0,8.0,...,0.27,0.65,0.31,0.58,0.44,0.22,0.66,0.39,0.61,Manchester City
4,Kyle Walker,eng ENG,DF,33.0,32,30,2767.0,30.7,0.0,4.0,...,0.13,0.13,0.00,0.13,0.01,0.09,0.10,0.01,0.10,Manchester City

In [51]:
city2=df2.loc[df2['team']=='Man City',['name', 'now_cost','web_name']]
city2

                                   name  now_cost        web_name
461                       Manuel Akanji        49          Akanji
462                          Nathan Aké        50             Aké
463                      Julián Álvarez        68       J.Alvarez
464  Bernardo Veiga de Carvalho e Silva        64  Bernardo Silva
465                          Oscar Bobb        44            Bobb
466                        João Cancelo        58         Cancelo
467                        Scott Carson        39          Carson
468                        Shea Charles        45         Charles
469                     Kevin De Bruyne       102       De Bruyne
470               Rúben Gato Alves Dias        55      Rúben Dias
471           Ederson Santana de Moraes        55         Ederson
472                          Phil Foden        76           Foden
473                       Jack Grealish        72        Grealish
474                      Erling Haaland       139         Haaland
475                       Mateo Kovačić        47         Kovačić
476                     Aymeric Laporte        49         Laporte
477                          Rico Lewis        43         R.Lewis
478                        Riyad Mahrez        75          Mahrez
479                Stefan Ortega Moreno        38   Stefan Ortega
480                      Máximo Perrone        44         Perrone
481                     Kalvin Phillips        47        Phillips
482                   Rodrigo Hernandez        56           Rodri
483                        Sergio Gómez        39    Sergio Gómez
484                        Zack Steffen        39         Steffen
485                         John Stones        53     John Stones
486                         Kyle Walker        53     Kyle Walker
487                  Matheus Luiz Nunes        48   Matheus Nunes
488                      Joško Gvardiol        48        Gvardiol
489                         Jeremy Doku        65            Doku
490                    Mahamadou Susoho        45          Susoho

In [52]:
# Create a new column 'final_name' starting with the 'name' column
city2['final_name'] = city2['name']

# Manually swap for specific players
city2.loc[city2['name'] == 'Bernardo Veiga de Carvalho e Silva', 'final_name'] = city2['web_name']
city2.loc[city2['name'] == 'Rodrigo Hernandez', 'final_name'] = city2['web_name']
city2.loc[city2['name'] == 'Rúben Gato Alves Dias', 'final_name'] = city2['web_name']
city2.loc[city2['name'] == 'Ederson Santana de Moraes', 'final_name'] = city2['web_name']
city2.loc[city2['name'] == 'Stefan Ortega Moreno', 'final_name'] = city2['web_name']
city2.loc[city2['name'] == 'Matheus Luiz Nunes', 'final_name'] = city2['web_name']
city2

,name,now_cost,web_name,final_name
461,Manuel Akanji,49,Akanji,Manuel Akanji
462,Nathan Aké,50,Aké,Nathan Aké
463,Julián Álvarez,68,J.Alvarez,Julián Álvarez
464,Bernardo Veiga de Carvalho e Silva,64,Bernardo Silva,Bernardo Silva
465,Oscar Bobb,44,Bobb,Oscar Bobb
466,João Cancelo,58,Cancelo,João Cancelo
467,Scott Carson,39,Carson,Scott Carson
468,Shea Charles,45,Charles,Shea Charles
469,Kevin De Bruyne,102,De Bruyne,Kevin De Bruyne
470,Rúben Gato Alves Dias,55,Rúben Dias,Rúben Dias
471,Ederson Santana de Moraes,55,Ederson,Ederson
472,Phil Foden,76,Foden,Phil Foden
473,Jack Grealish,72,Grealish,Jack Grealish
474,Erling Haaland,139,Haaland,Erling Haaland
475,Mateo Kovačić,47,Kovačić,Mateo Kovačić
476,Aymeric Laporte,49,Laporte,Aymeric Laporte
477,Rico Lewis,43,R.Lewis,Rico Lewis
478,Riyad Mahrez,75,Mahrez,Riyad Mahrez
479,Stefan Ortega Moreno,38,Stefan Ortega,Stefan Ortega
480,Máximo Perrone,44,Perrone,Máximo Perrone
481,Kalvin Phillips,47,Phillips,Kalvin Phillips
482,Rodrigo Hernandez,56,Rodri,Rodri
483,Sergio Gómez,39,Sergio Gómez,Sergio Gómez
484,Zack Steffen,39,Steffen,Zack Steffen
485,John Stones,53,John Stones,John Stones
486,Kyle Walker,53,Kyle Walker,Kyle Walker
487,Matheus Luiz Nunes,48,Matheus Nunes,Matheus Nunes
488,Joško Gvardiol,48,Gvardiol,Joško Gvardiol
489,Jeremy Doku,65,Doku,Jeremy Doku
490,Mahamadou Susoho,45,Susoho,Mahamadou Susoho

In [55]:
city_2f=city2.loc[df2['team']=='Man City',['final_name', 'now_cost']]
city_2f.rename(columns={'final_name':'Player'}, inplace=True)
city_2f

               Player  now_cost
461     Manuel Akanji        49
462        Nathan Aké        50
463    Julián Álvarez        68
464    Bernardo Silva        64
465        Oscar Bobb        44
466      João Cancelo        58
467      Scott Carson        39
468      Shea Charles        45
469   Kevin De Bruyne       102
470        Rúben Dias        55
471           Ederson        55
472        Phil Foden        76
473     Jack Grealish        72
474    Erling Haaland       139
475     Mateo Kovačić        47
476   Aymeric Laporte        49
477        Rico Lewis        43
478      Riyad Mahrez        75
479     Stefan Ortega        38
480    Máximo Perrone        44
481   Kalvin Phillips        47
482             Rodri        56
483      Sergio Gómez        39
484      Zack Steffen        39
485       John Stones        53
486       Kyle Walker        53
487     Matheus Nunes        48
488    Joško Gvardiol        48
489       Jeremy Doku        65
490  Mahamadou Susoho        45

In [59]:
city_final=city1.merge(city_2f, on='Player', how='inner')
city_final

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,G+A_90,G-PK_90,G+A-PK_90,xG_90,xAG_90,xG+xAG_90,npxG_90,npxG+xAG_90,Team,now_cost
0,Rodri,es ESP,MF,27.0,34,34,2931.0,32.6,8.0,9.0,...,0.52,0.25,0.52,0.12,0.12,0.24,0.12,0.24,Manchester City,56
1,Phil Foden,eng ENG,"FW,MF",23.0,35,33,2857.0,31.7,19.0,8.0,...,0.85,0.60,0.85,0.33,0.26,0.59,0.33,0.59,Manchester City,76
2,Ederson,br BRA,GK,29.0,33,33,2785.0,30.9,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester City,55
3,Julián Álvarez,ar ARG,"MF,FW",23.0,36,31,2647.0,29.4,11.0,8.0,...,0.65,0.31,0.58,0.44,0.22,0.66,0.39,0.61,Manchester City,68
4,Kyle Walker,eng ENG,DF,33.0,32,30,2767.0,30.7,0.0,4.0,...,0.13,0.00,0.13,0.01,0.09,0.10,0.01,0.10,Manchester City,53
5,Bernardo Silva,pt POR,"MF,FW",28.0,33,29,2578.0,28.6,6.0,9.0,...,0.52,0.21,0.52,0.13,0.27,0.40,0.13,0.40,Manchester City,64
6,Erling Haaland,no NOR,FW,23.0,31,29,2552.0,28.4,27.0,5.0,...,1.13,0.71,0.88,1.03,0.15,1.18,0.81,0.96,Manchester City,139
7,Rúben Dias,pt POR,DF,26.0,30,28,2559.0,28.4,0.0,0.0,...,0.00,0.00,0.00,0.05,0.01,0.06,0.05,0.06,Manchester City,55
8,Manuel Akanji,ch SUI,"DF,MF",28.0,30,28,2511.0,27.9,2.0,0.0,...,0.07,0.07,0.07,0.07,0.02,0.09,0.07,0.09,Manchester City,49
9,Joško Gvardiol,hr CRO,DF,21.0,28,26,2328.0,25.9,4.0,1.0,...,0.19,0.15,0.19,0.12,0.06,0.18,0.12,0.18,Manchester City,48
10,Nathan Aké,nl NED,DF,28.0,29,24,2042.0,22.7,2.0,2.0,...,0.18,0.09,0.18,0.11,0.05,0.16,0.11,0.16,Manchester City,50
11,Jeremy Doku,be BEL,"FW,MF",21.0,29,18,1595.0,17.7,3.0,8.0,...,0.62,0.17,0.62,0.14,0.26,0.40,0.14,0.40,Manchester City,65
12,Mateo Kovačić,hr CRO,MF,29.0,30,16,1551.0,17.2,1.0,0.0,...,0.06,0.06,0.06,0.07,0.09,0.17,0.07,0.17,Manchester City,47
13,Kevin De Bruyne,be BEL,MF,32.0,18,15,1221.0,13.6,4.0,10.0,...,1.03,0.29,1.03,0.18,0.85,1.03,0.18,1.03,Manchester City,102
14,John Stones,eng ENG,"DF,MF",29.0,16,12,1064.0,11.8,1.0,0.0,...,0.08,0.08,0.08,0.09,0.02,0.11,0.09,0.11,Manchester City,53
15,Jack Grealish,eng ENG,"FW,MF",27.0,20,10,1009.0,11.2,3.0,1.0,...,0.36,0.27,0.36,0.19,0.22,0.41,0.19,0.41,Manchester City,72
16,Rico Lewis,eng ENG,"DF,MF",18.0,16,8,809.0,9.0,2.0,0.0,...,0.22,0.22,0.22,0.07,0.12,0.19,0.07,0.19,Manchester City,43
17,Matheus Nunes,pt POR,MF,24.0,17,7,661.0,7.3,0.0,2.0,...,0.27,0.00,0.27,0.11,0.15,0.27,0.11,0.27,Manchester City,48
18,Stefan Ortega,de GER,GK,30.0,9,5,635.0,7.1,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester City,38
19,Oscar Bobb,no NOR,"FW,MF",20.0,14,2,302.0,3.4,1.0,1.0,...,0.60,0.30,0.60,0.41,0.37,0.78,0.41,0.78,Manchester City,44
20,Kalvin Phillips,eng ENG,MF,27.0,4,0,93.0,1.0,0.0,0.0,...,0.00,0.00,0.00,0.07,0.00,0.07,0.07,0.07,Manchester City,47
21,Sergio Gómez,es ESP,"FW,MF",22.0,6,0,53.0,0.6,0.0,1.0,...,1.70,0.00,1.70,0.41,0.31,0.73,0.41,0.73,Manchester City,39
22,Aymeric Laporte,es ESP,DF,29.0,1,0,12.0,0.1,0.0,0.0,...,0.00,0.00,0.00,0.27,0.00,0.27,0.27,0.27,Manchester City,49

In [64]:
df['Team'].unique()

array(['Manchester City', 'Liverpool', 'Arsenal', 'Chelsea',
       'Newcastle United', 'Tottenham Hotspur', 'Manchester United',
       'Aston Villa', 'West Ham United', 'Crystal Palace', 'Fulham',
       'Everton', 'Brighton', 'Bournemouth', 'Wolverhampton', 'Brentford',
       'Nottingham Forest', 'Luton Town', 'Burnley', 'Sheffield United'],
      dtype=object)